platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: resource-music-repo

outputs:
  - name: output

run:
  path: mvn
  args: ["-f", "resource-music-repo/pom.xml", "package"]

run:
  path: mv
  args: ["-f", "resource-music-repo/target/spring-music.war", "output/spring-music.war"]
