platform: linux

image_resource:
  type: s3
  source:
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    endpoint: {{s3_endpoint}}
    bucket: {{s3_bucket}}
    regexp: "maven"


inputs:
  - name: resource-music-repo

outputs:
  - name: output

run:
  path: sh
  args:
    - resource-music-repo/ci/tasks/maven-package.sh
