platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: resource-music-repo

outputs:
  - name: war-file
    path: resource-music-repo/target/

run:
  path: mvn
  args: ["-f", "resource-music-repo/pom.xml", "package"]
