platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: resource-music-repo

#outputs:
#  - name: jar-file
#    path: git-repo/target/

run:
  path: mvn
  args: ["-f", "resource-music-repo/pom.xml", "-DskipTests=true", "package"]
