platform: linux
image_resource:
  type: s3
  source:
    s3_access_key_id:
    s3_secret_access_key:
    s3_endpoint:
    s3_bucket:
    regexp: "maven"
inputs:
  - name: resource-music-repo
outputs:
  - name: output
run:
  path: sh
  args:
    - resource-music-repo/ci/tasks/maven-package.sh
