---
resources:
- name: maven-image-to-package
  type: docker-image
  source:
    repository: maven       # UPDATE THIS with the targeted image repo name
    tag: 3.5-jdk-8-alpine               # UPDATE THIS with the desired tag of the image

- name: my-maven-image-s3
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    bucket: ((s3_bucket))
    endpoint: ((s3_endpoint))
    secret_access_key: ((s3_secret_access_key))
    regexp: maven/maven-(.*).tgz

jobs:
- name: Download-And-Package-Maven-Image
  plan:
  - get: maven-image-to-package
    params:
      rootfs: true
  - task: prepare-image-to-export
    config:
      platform: linux
      inputs:
        - name: maven-image-to-package
      outputs:
        - name: maven
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: sh
        args:
        - -exc
        - |
          echo "Exporting ubuntu image"
          mkdir export-directory && cd export-directory
          cp ../maven-image-to-package/metadata.json .
          mkdir rootfs
          tar -xvf ../maven-image-to-package/rootfs.tar -C ./rootfs/ --exclude="dev/*"
          cd rootfs
          cd ../..
          echo "Packaging maven image"
          tmp_version="1.0"
          tar -czf "maven/maven-${tmp_version}.tgz" -C export-directory .
          ls -la maven
  - put: my-maven-image-s3
    params:
      file: "maven/maven-*.tgz"
