resources:
- name: resource-music-repo
  type: git
  source:
    uri: https://github.com/poprygun/spring-music.git
    branch: master

- name: resource-deploy-web-app
  type: cf
  source:
    api: https://api.run.pez.pivotal.io
    username: {{api-username}}
    password: {{api-password}}
    organization: pivot-ashumilov
    space: development
    skip_cert_check: true

- name: time
  type: time
  source:
    interval: 60s

jobs:
  - name: deploy-pez
    plan:
    - aggregate:
      - get: resource-music-repo
        trigger: true
      - get: time
    - task: maven-package
      privileged: true
      file: resource-music-repo/ci/tasks/maven-package.yml
    - put: resource-deploy-web-app
      params:
        manifest: resource-music-repo/manifest.yml
        path: output/spring-music.war