resources:
- name: resource-music-repo
  type: git
  source:
    uri: https://github.com/poprygun/spring-music.git
    branch: master

- name: resource-deploy-web-app
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{api-username}}
    password: {{api-password}}
    organization: {{api-org}}
    space: {{api-space}}
    skip_cert_check: true

jobs:
  - name: deploy-pws
    plan:
    - aggregate:
      - get: resource-music-repo
        trigger: true
    - task: maven-package
      file: resource-music-repo/ci/tasks/maven-package.yml
    - put: resource-deploy-web-app
      params:
        manifest: resource-music-repo/manifest.yml
        path: output/spring-music.war
